src/main/java/com/sforce/ws/bind/TypeMapper.java, src/main/java/com/sforce/ws/codegen/Generator.java, src/main/java/com/sforce/ws/codegen/TypeMetadataConstructor.java, src/main/java/com/sforce/ws/wsdl/Constants.java, src/main/java/com/sforce/ws/wsdl/SfdcApiType.java
This code change is for adding tooling API support to SfdcApiType and generating AggregateResult.java when processing tooling.wsdl.
=> Support Tooling API and generate AggregateResult.java for Tooling API

pom.xml, src/main/java/com/sforce/ws/ConnectorConfig.java, src/main/java/com/sforce/ws/bind/ArrayCodec.java, src/main/java/com/sforce/ws/wsdl/SfdcApiType.java
@guanzhijie @wgray-sfdc Some changes were required to your commits, FYI.
=> Fixes for ToolingConnection, Guava usage.

src/main/java/com/sforce/ws/transport/SoapConnection.java
=> Add 'Illegal Session' to list of messages that trigger SessionRenewal

src/main/java/com/sforce/ws/ConnectorConfig.java, src/main/java/com/sforce/ws/transport/SoapConnection.java, src/main/java/com/sforce/ws/transport/TransportFactory.java
Add TransportFactory to facilitate usage of non-statically configurable Transport instances.
=> Add TransportFactory

src/main/java/com/sforce/ws/bind/TypeMapper.java
W-2690600 Adding java data types to keywords so they will escape properly in enum type file generation
=> W-2690600 Adding java data types to keywords so they will escape properly in enum type file generation

src/main/java/com/sforce/ws/transport/GaeHttpTransport.java
=> Validate certificates.

pom.xml, src/main/java/com/sforce/ws/bind/TypeMapper.java, src/main/java/com/sforce/ws/bind/XmlObject.java, src/main/java/com/sforce/ws/bind/XmlObjectWrapper.java, src/main/java/com/sforce/ws/parser/XmlInputStream.java
=> Allow for retrieving complex types from XmlObject.

src/main/java/com/sforce/async/BulkConnection.java, src/main/java/com/sforce/async/TransformationSpecRequest.java
[Data fields mapping](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_mapping.htm) with ``BulkConnection#createTransformationSpec`` is not worked due to a following error:
```
Exception in thread "main" [AsyncApiException  exceptionCode='ClientInputError'
exceptionMessage='Failed to parse exception'
]
at com.sforce.async.BulkConnection.parseAndThrowException(BulkConnection.java:169)
at com.sforce.async.TransformationSpecRequest.completeRequest(TransformationSpecRequest.java:79)
at sample.BulkExample.runSample(BulkExample.java:57)
at sample.BulkExample.main(BulkExample.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at …
```
=> Fix: a transformation spec cannot be uploaded

src/main/java/com/sforce/ws/bind/TypeMapper.java
This set of changes to support Big decimal in the api.
=> Supporting Big Decimal in the API

src/main/java/com/sforce/ws/codegen/templates/type.st
http://www.brsanthu.com/blog/2011/03/web-service-connector-wsc-and-duplicate-boolean-getters/
=> Fix Duplicate boolean Getters

src/main/java/com/sforce/ws/transport/SoapConnection.java, src/test/java/com/sforce/ws/transport/SoapConnectionTest.java
This pull requests contains the following parts
1) Throwing an exception if we encounter a header that is not registered with a connection
2) Re-writing the loop so that is more readable.
=> Adding an exception for unrecognized header.

src/main/java/com/sforce/ws/codegen/templates/type.st, src/test/resources/codegeneration/EmailSyncEntity.java, src/test/resources/codegeneration/EmailSyncEntityInterface.java
Fix "code to large" error in generated toString method
=> Refactor tostring

README.md, pom.xml
This is something we've been wanting to do for a while. I had the project open, so I figured I'd just take care of it.
=> adding Main-Class attribute to JAR manifest

README.md, src/main/java/com/sforce/ws/bind/XmlObject.java
=> Closing #46

src/main/java/com/sforce/async/StatusCode.java
=> Checkin to fix #173

src/main/java/com/sforce/ws/codegen/templates/type.st, src/test/resources/codegeneration/EmailSyncEntity.java, src/test/resources/codegeneration/EmailSyncEntityInterface.java
=> More changes to make sure CodeTooLarge issue never happens,

src/main/java/com/sforce/async/StatusCode.java
Adding PLATFORM_EVENT_PUBLISHING_UNAVAILABLE and OPERATION_ENQUEUED status code enum values
=> Add operation enqueued status code

pom.xml, src/main/java/com/sforce/ws/bind/XmlObjectWrapper.java
Fix #230. Suppress class property when introspecting using PropertyUtils.
=> Fix CVE-2014-0114

pom.xml, src/main/java/com/sforce/ws/types/OffsetDate.java
1. Upgrade maven shade from 2.0 -> 3.2.1
2. Add a license hader to OffsetDate.java
=> Fix build problem with WSC

README.md, pom.xml, src/main/java/com/sforce/async/OperationEnum.java
What changed: 
- Added`OperationEnum internal` associated with [this work item](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000yrn5BYAQ/view) / TD filed by Commerce Product Import team
- Waiting on discussion on when to release new WSC version 57.0.0 before closing this PR
=> Add internal operation enum;

BUILD.bazel
=> Update WSC to make Spring compatible to 6.2
