forcedotcom/wsc

src/main/java/com/sforce/ws/bind/ArrayCodec.java
src/main/java/com/sforce/ws/bind/TypeMapper.java
src/main/java/com/sforce/ws/bind/XmlObject.java
src/test/java/com/sforce/ws/bind/ArrayCodecTest.java
src/test/java/com/sforce/ws/bind/XmlObjectTest.java

Support for String[] as an atomic value.  
In a perfect world, we would use a ready-built codec, such as in Axis, or even java.beans.  However, The data-flow does not easily allow insertion of additional nodes to the XML out stream, as it assumes any value is immediately serializable to a String, which is subsequently escaped when injected into the document.
As an alternative, a simple codec using URL-encoding allows us to freely use non-alpha characters in our serialization (specifically [,]").  This allows for a readable XML document and fits into the existing architecture of the client.
A third alternative, involved converting String->byte[]->Base64, but this was rejected as it would render the output XML unreadable.

String array support

---

pom.xml

String array support no longer needs guava.

Remove guava as it is no longer necessary.

---

pom.xml

When running deploy, include the uber jar.
Fix the Javadoc issue on JDK 8 where it would error out.
Should be two pull requests, but oops.

Include uber jar in deploy and fix Javadoc issue

---

pom.xml

Fix bugs with previous pull, sorry.

Fix shading for uber jar and javadoc on JDK < 1.8.

---

src/main/java/com/sforce/async/SObject.java

The purpose of this change is to facilitate traversal of the SObject tree.

Getter for field references in SObject

---

src/main/java/com/sforce/async/BulkConnection.java

Make JSON deserializer work on BatchResults. In previous code JSON parser didn't know how to handle it.

add JSON support for getBatchResults

---

src/main/java/com/sforce/ws/parser/XmlOutputStream.java

It would be helpful to be able to use try-with-resources on XmlOutputStreams.

Making the XmlOutputStream AutoCloseable for convenience

---

src/main/java/com/sforce/async/BatchRequest.java
src/main/java/com/sforce/async/BulkConnection.java
src/main/java/com/sforce/async/CsvBatchRequest.java
src/main/java/com/sforce/async/TransformationSpecRequest.java
src/test/java/com/sforce/async/BulkConnectionTest.java

There were gaps in the JSON support for Bulk API, specifically around parsing errors coming back from the server. This change parameterizes the error parsing code with a content type. For XML and CSV jobs, the errors will be in XML. For JSON jobs, the errors will be in JSON.

More JSON support for Bulk API in WSC

---

src/main/java/com/sforce/async/BulkConnection.java
src/test/java/com/sforce/async/BulkConnectionTest.java

The attached PR solves Issue #125.  However, the proper solution is to update the maven-license-plugin license.txt file to reflect a revised copyright notice.  This will require all module copyright notices to be revised to match the contents of the license.txt file to avoid the issue this PR temporarily resolves.

Modify copyright statement to match copyright template required by maven-license-plugin

---

src/main/java/com/sforce/ws/bind/TypeMapper.java
src/main/java/com/sforce/ws/codegen/Generator.java
src/main/java/com/sforce/ws/codegen/templates/extendedErrorDetails.st
src/test/resources/codegeneration/ExtendedErrorDetails.java

Adding a custom template for supporting <any/> on the loosely typed ExtendedErrorDetails section of the wsdl

Add ExtendedErrorDetails custom template for supporting <any/> tag

---

src/main/java/com/sforce/ws/codegen/Generator.java

ExtendedErrorDetails weren't getting generated for non-sObject wsdl which wasn't the right thing to do.
https://gus.my.salesforce.com/a07B000000231ASIAY

force-wsc v37.0 seems to balk on ExtendedErrorDetails when generating WSDLs from 202/patch

---

src/main/java/com/sforce/ws/bind/TypeMapper.java
src/main/java/com/sforce/ws/codegen/Generator.java
src/main/java/com/sforce/ws/codegen/templates/extendedErrorDetails.st
src/main/java/com/sforce/ws/codegen/templates/iExtendedErrorDetails.st

1. Generate generic class for ExtendedErrorDetails when an unknown wsdl is given. getField(...) will not be available for xsd:any when an unknown wsdl is given
2. Interface is generated for ExtendedErrorDetails when needed.

Changes to support ExtendedErrorDetails with all types of wsdls

---

src/main/java/com/sforce/ws/bind/DateCodec.java

According to sfdc documentation, dates in the soap api are transmitted in UTC.
The connector is correctly serializing them in UTC in the CalendarCodec class, but is deserializing using local time in the DateCodec class.

Deserialize dates in UTC timezone

---

src/main/java/com/sforce/async/BulkConnection.java

Related issue: forcedotcom/wsc#161
The exception is thrown when the response for an HTTP GET does not include XML or JSON content type. No tests added. Existing tests passing on my local environment.

Fixes the occational NullPointerException

---

src/main/java/com/sforce/async/BulkConnection.java
src/main/java/com/sforce/ws/ConnectorConfig.java
src/main/java/com/sforce/ws/transport/JdkHttpTransport.java

Add ability to set SSLContext on ConnectorConfig, use the custom SSLContext (if present) when creating connections in SOAP and Bulk APIs. Fixes #213.

Add ability to set SSLContext on ConnectorConfig

---

src/main/java/com/sforce/async/BulkConnection.java

Came across this when code would run on OS X but not on Windows. Without this, on windows, the files that are pushed to Salesforce as the batch request contain the full path as well as the filename, and the API throws an error that it cannot locate a file that is mentioned in request.txt.

Fix for OS-independent generation of batches from directories.

---

src/main/java/com/sforce/async/AsyncExceptionCode.java

When TransactionSecurityPolicies execute and take a block action during bulk api, the action is still taken but the action is mapped to an unknown exception. So adding a TransactionSecurityBlock code for those cases.
TransactionSecurityInternalError is used when policy execution hit some kind of internal salesforce developer error like NullPointerException.
TransactionSecurityDeveloperError is used when customer policies hit a customer developer exception, like customer apex policy hits a NullPointerException.

Update AsyncExceptionCode for Transaction Security

---

src/main/java/com/sforce/ws/tools/wsdlc.java

I am facing an issue while integrating wsc 49.0.0 release in Salesforce core. I believe the issue is caused by https://github.com/forcedotcom/wsc/commit/6698f255700b96142fbf81a658299ef27f4f6253 commit where we have added one more argument when instantiating wsdlc. In that commit, we are passing new arg javaTime as false in all existing calls to wsc.

adding back the constructor with 2 arguments

---

pom.xml
src/main/java/com/sforce/async/BulkConnection.java
src/main/java/com/sforce/async/Error.java
src/main/java/com/sforce/async/JobInfo.java
src/test/java/com/sforce/ws/codegen/AggregateCodeGeneratorTest.java
src/test/java/com/sforce/ws/codegen/CodeGeneratorTestUtil.java
src/test/java/com/sforce/ws/codegen/ComplexTypeCodeGeneratorTest.java
src/test/java/com/sforce/ws/codegen/ConnectionCodeGeneratorTest.java
src/test/java/com/sforce/ws/codegen/ConnectorCodeGeneratorTest.java
src/test/java/com/sforce/ws/codegen/SObjectCodeGeneratorTest.java
src/test/java/com/sforce/ws/codegen/SimpleTypeCodeGeneratorTest.java
src/test/java/com/sforce/ws/codegen/VoidReturnTest.java

I've made a variety of fixes and updates to fix a few issues, most notably being security scan failures with the owasp dependency checking tool but also including fixes for tests when run under windows and/or jdk 11+

Dependency upgrades, fixes for running under windows, jdk 11

---

README.md
src/main/java/com/sforce/ws/codegen/Compiler.java
src/main/java/com/sforce/ws/codegen/Generator.java
src/main/java/com/sforce/ws/tools/wsdlc.java

Fix for issue https://github.com/forcedotcom/wsc/issues/222
We were dependent on tools.jar to get compiler class supplied within JDK and we were using reflection to use compile methods, however, with JDK9+, tools.jar are no longer provided and hence we are switching to use JavaCompiler API to locate and supply compiler for us to compile the autogenerated java stubs.
This fix has been tested locally with Enterprise.wsdl, Apex.wsdl, metadata.wsdl and Partner.wsdl and I have also tested the integration of this fix into core.

refactored Compiler.java class to use Java Compiler API

---

src/main/java/com/sforce/ws/bind/TypeMapper.java
src/test/java/com/sforce/ws/bind/TypeMapperTests.java

Haven't write on Java for a while... and did this silly mistake. Initialization order does matter! javaTime field was updated **after** initialization of hash maps :-( and actual value of it was ignored (like it was always false).
And the unit test wasn't actually testing this important part... Fixed it now, updated unit test and reorganizes code to make it impossible to reappear in future.
@reubencornel could you please merge it and release fix for it? Appreciate it.
CC: @khaledez

fix non-working java-time feature #235 and update test

---

src/main/java/com/sforce/async/CSVReader.java

To support long text and rich text fields.
Fixes #182.

Increase maximum size of CSV cell to 131072

---

pom.xml

- Have put in the detailed explanation in the following quip document : https://salesforce.quip.com/VUxtAbkBafzu for steps
- Have updated versions to the latest non-vulnerable version where possible.
- False positives were being reported after updation because of the dependency check tool being outdated have updated it 8.4.1

@W-15110789 Review WSC depedencies 

---

README.md
pom.xml

As per the requirements from the CARE team we want to update the Jackson to be 2.18 to ensure Spring 6.2 compatibility , also the spike mentions the path for it here : 
https://docs.google.com/document/d/1l2gsz-v2FJOg8FsVdfsaFXBAi-P8TN4OqOJZyCH116o/edit?tab=t.0

[WSC Specific] Make Jackson 2.18 and Exclude Meta-INF Files
